[package]
name = "rostfrei-structure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
include = ["src/**", "templates/**", "Cargo.toml"]

[lib]
name = "rostfrei_structure"

[[bin]]
name = "cargo-rostfrei"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
heck.workspace = true
proc-macro2 = { workspace = true, features = ["span-locations"] }
serde.workspace = true
serde_json.workspace = true
syn = { workspace = true, features = ["visit"] }
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
toml = "1.1"
