mod add_bicycle;
mod aggregate;
pub(in crate::domain) mod assess_rental_eligibility;
mod bicycle;
mod bicycle_availability;
mod fleet_consistency;
mod identity;
mod import_rental_fleet;
mod initialize;
mod rent_bicycle;
mod return_bicycle;
mod root;
mod stream;

pub use add_bicycle::{AddBicycle, AddBicycleActions, BicycleAdded};
pub use aggregate::RentalFleetAggregate;
pub use bicycle::{Bicycle, BicycleCondition, BicycleId, BicycleRentalLifecycle, BicycleStatus};
pub use bicycle_availability::BicycleAvailability;
pub(in crate::domain) use bicycle_availability::BicycleAvailabilityQueries;
pub use identity::FleetId;
pub(crate) use import_rental_fleet::ImportRentalFleetActions;
pub use import_rental_fleet::{ImportRentalFleetInput, ImportedBicycle, RentalFleetImported};
pub use rent_bicycle::{BicycleRented, BicycleUnavailable, RentBicycle, RentBicycleActions};
pub use return_bicycle::{BicycleNotRented, BicycleReturned, ReturnBicycle, ReturnBicycleActions};
pub use root::RentalFleet;
pub use stream::stream_id;
