[package]
name = "rostfrei"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
rostfrei-core = { path = "../rostfrei-core", version = "0.1.0" }
rostfrei-domain = { path = "../rostfrei-domain", version = "0.1.0" }
rostfrei-domain-runtime = { path = "../rostfrei-domain-runtime", version = "0.1.0" }
rostfrei-messaging-core = { path = "../rostfrei-messaging-core", version = "0.1.0" }
rostfrei-registry = { path = "../rostfrei-registry", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
trybuild.workspace = true

[lints]
workspace = true
