[package]
name = "rostfrei"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rostfrei-core = { path = "../rostfrei-core", version = "0.1.0" }
rostfrei-domain = { path = "../rostfrei-domain", version = "0.1.0" }
rostfrei-domain-runtime = { path = "../rostfrei-domain-runtime", version = "0.1.0" }
rostfrei-registry = { path = "../rostfrei-registry", version = "0.1.0" }

[dev-dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
trybuild.workspace = true

[lints]
workspace = true
