[package]
name = "rostfrei-domain-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rostfrei-core.workspace = true
rostfrei-domain.workspace = true
rostfrei-registry.workspace = true

[dev-dependencies]
async-trait.workspace = true
serde.workspace = true

[lints]
workspace = true
