[package]
name = "bike-rental"
default-run = "bike-rental-api"
version.workspace = true
edition = "2024"
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
rostfrei = { path = "../../crates/rostfrei" }
rostfrei-control-plane = { path = "../../crates/rostfrei-control-plane", features = ["http"] }
rostfrei-messaging-core = { path = "../../crates/rostfrei-messaging-core" }
rostfrei-nats = { path = "../../crates/rostfrei-nats" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
