[package]
name = "rostfrei-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild.workspace = true
zs-registry = { package = "rostfrei-registry", path = "../rostfrei-registry" }

[lints]
workspace = true
