[package]
name = "rostfrei-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
rostfrei-messaging-core = { path = "../rostfrei-messaging-core" }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
