[package]
name = "rostfrei-fixtures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rostfrei-core = { path = "../rostfrei-core" }
rostfrei-messaging-core = { path = "../rostfrei-messaging-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true

[lints]
workspace = true
