[package]
name = "rostfrei-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
rostfrei-core.workspace = true
rostfrei-domain.workspace = true
rostfrei-messaging-core.workspace = true

[dev-dependencies]
async-trait.workspace = true

[lints]
workspace = true
